name: basic pip CI tests

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]  #[macOS-latest, ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10']   # quotes needed to avoid trimming 3.10

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt

    - name: Install package
      run: |
        python -m pip install . --no-deps
        python --version
        python -c "import sys; print(f'Python {sys.version}')"
        python -c "import pip; print(f'pip {pip.__version__}')"
        python -c "import setuptools; print(f'setuptools {setuptools.__version__}')"
        python -m pip freeze

    - name: Run tox
      # Run tox using the version of Python in `PATH`
      run: tox -e py

    # - name: Run tests
    #   run: |
    #      python ./convert_notebook_tests.py
    #      bash ./scripts/tester.sh -b -v

    # - name: CodeCov
    #   uses: codecov/codecov-action@v1
    #   with:
    #     file: ./coverage.xml
    #     flags: unittests
    #     name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
